name: Toolset Test

on:
    pull_request:
    push:
        branches:
            - main

jobs:
  cmake-test:
    runs-on: ubuntu-24.04
    container:
      image: ghcr.io/almalinux/8-base:latest
    strategy:
      fail-fast: false
      matrix:
        toolset-version: ['9', '10', '11', '12', '13', '14']
        build_shared_libs: ['ON', 'OFF']

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: latest

      - name: Check version
        run: cmake --version

      - name: Configure
        run: |
          cmake -S . -B /tmp/build \
            -DBUILD_WITH_STATS=ON \
            -DBUILD_DDDMP=ON \
            -DBUILD_TESTS=ON \
            -DBUILD_SHARED_LIBS=${{ matrix.build_shared_libs }}

      - name: Build
        run: cmake --build /tmp/build

      - name: Test 
        run: ctest --test-dir /tmp/build --output-on-failure

      - name: Install
        run: cmake --install /tmp/build --prefix /tmp/install
