name: Test

on:
  pull_request:
    branches:
      - main
      - 4.0.0
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  cmake-test:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake ninja-build catch2

      - name: Configure
        run: |
          cmake -S . -B /tmp/build \
            -DCUDD_BUILD_WITH_STATS=ON \
            -DCUDD_BUILD_TESTS=ON

      - name: Build
        run: cmake --build /tmp/build

      - name: Test 
        run: ctest --test-dir /tmp/build --output-on-failure
