name: cudd

on:
    pull_request:
    push:
        branches:
            - main

jobs:
  cmake-test:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        cmake-version: ['3.22', '3.25', '3.25', '3.30', 'latest']
        build_shared_libs: ['ON', 'OFF']

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: ${{ matrix.cmake-version }}

      - name: Configure
        run: |
          cmake -S . -B /tmp/build \
            -DBUILD_SHARED_LIBS=${{ matrix.build_shared_libs }}
            -DBUILD_WITH_STATS=ON \
            -DBUILD_DDDMP=ON \
            -DBUILD_TESTS=ON

      - name: Build
        run: cmake --build /tmp/build

      - name: Test 
        run: ctest --test-dir /tmp/build --output-on-failure

      - name: Install
        run: cmake --install /tmp/build --prefix /tmp/install
