name: GCC Build Test

on:
    pull_request:
    push:
        branches:
            - main
            - 4.0.0

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  gcc-test:
    runs-on: ubuntu-24.04
    container:
      image: docker.io/gcc:${{ matrix.gcc-version }}
    strategy:
      fail-fast: false
      matrix:
        gcc-version: ['10', '11', '12', '13', '14', '15']
        build-shared-libs: ['ON', 'OFF']

    env:
      CMAKE_C_COMPILER: gcc
      CMAKE_CXX_COMPILER: g++

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: "3.26"

      - name: Configure
        run: |
          cmake -S . -B /tmp/build \
            -DCUDD_BUILD_SHARED_LIBS=${{ matrix.build-shared-libs }}

      - name: Build
        run: cmake --build /tmp/build

      - name: Install
        run: cmake --install /tmp/build --prefix /tmp/install
